### ISSUE TITLE
Gateway issue: End of book links in the navigation do not work

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-rulesets#177]
When clicking on the link to a composite page (end of book link) in the navigation, the drop down is toggled but user isn't taken to the url.

This applies to Statistics and AP Biology

**Comment by chcase** [comment]
@helenemccarron the end of book content won’t load until the structure is updated to include the extra layer. Curently the end of book content is being created but b/c there isn’t any resource level content there are no resources which is why the navigation doesn’t work. The end of book content structure needs to match the other chapters.

**Comment by helenemccarron** [comment]
As discussed during our last meeting, we updated the structure for the appendices (in Statistics) to contain the structure required (binder, resources, section) but they do not seem to work. The index page matches the `composite-page` structure, which didn't require a section to display properly per our last conversation.

**Comment by chcase** [comment]
@helenemccarron  Yep that's correct although when looking at the TOC for the HS Statistics book (TEAhsstatistics/contents/bed1f9d3-7472-4640-9947-7b87d81303ab.xhtml) the end of book content doesn't have the next level needed for the resource creation.  For example 14. Appendix A Review Exercises (Ch 3-13) would need to have another level for 1. Appendix A Review Exercises (Ch 3-13) [or whatever you'd want it titled] then that level is the level used for resource creation.

**Comment by helenemccarron** [comment]
Appendix A Review Exercises (Ch 3-13) seems to contain a section and a title (Chapter 3) in a `h3`. There is some content before that appears before but the section containing the subtitle should display, shouldn't it?

**Comment by chcase** [comment]
@helenemccarron  the structure of the Appendix A files seems to be correct but the TOC needs to have the same structure as the other chapters with the top level as the binder/chapter then the next level is used as the resource (so that's the one that would need to link to f258bb2d-c121-4d0c-a341-d4a30d5721f0@4.xhtml). Right now the end of book content doesn't have that second layer that's needed for resource creation.

**Comment by helenemccarron** [comment]
@chcase Understood, we will look into creating that part in the TOC as well.

**Comment by chcase** [comment]
sounds good.  Let me know if you have any other questions
