### ISSUE TITLE
Gateway issue: content is out of order

### ISSUE THREAD

**Issue by helenemccarron** [Connexions/cnx-rulesets#178]
https://stg.texasgateway.org/resource/21-atoms-isotopes-ions-and-molecules-building-blocks

The sections within a resources are sometimes out of order.

**Comment by chcase** [comment]
@helenemccarron the end of book content won’t load until the structure is updated to include the extra layer.  Curently the end of book content is being created but b/c there isn’t any resource level content there are no resources which is why the navigation doesn’t work.    The end of book content structure needs to match the other chapters.

**Comment by helenemccarron** [comment]
@chcase  I believe this refers to issue #177? I'll comment there.

**Comment by chcase** [comment]
yep sorry! had the wrong one open so I moved it over

**Comment by chcase** [comment]
@helenemccarron  I was able to reproduce the issue with content out of order.  We are looking into the fix.   Seems to correct in the edit view

**Comment by chcase** [comment]
@helenemccarron  - I realize that we'll have new books to import soon but wanted to let you know the content out of order issue should be resolved.  Let me know if you continue to see the issue

**Comment by helenemccarron** [comment]
@chcase thank you! Will do.
